services:

  agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1416:1416"
    networks:
      - mynetwork

  openweb-ui:
    container_name: openweb-ui
    image: "ghcr.io/open-webui/open-webui:main"
    restart: always
    environment:
      - HTTP_PROXY=
      - HTTPS_PROXY=
      - http_proxy=
      - https_proxy=
      - OPENAI_API_BASE_URL=http://agent:1416/v1
      - ENABLE_OLLAMA_API=False
      - WEBUI_AUTH=False
      - GLOBAL_LOG_LEVEL=DEBUG
      - HF_HUB_OFFLINE=1
      - TRANSFOMRERS_OFFLINE=1
      - RAG_EMBEDDING_MODEL=
    volumes:
      - ./openweb_ui_data:/app/backend/data
    ports:
      - "2000:8080"
    networks:
      - mynetwork

  opensearch:
    image: opensearchproject/opensearch:latest
    restart: always
    container_name: opensearch
    ports:
      - 9200:9200
      - 9600:9600
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - DISABLE_INSTALL_DEMO_CONFIG=true # Prevents execution of bundled demo script which installs demo certificates and security configurations to OpenSearch
      - DISABLE_SECURITY_PLUGIN=true
    volumes:
      - ./opensearch-data:/usr/share/opensearch/data
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge